environment:
  matrix:
  - TOXENV: "py26"
  - TOXENV: "py27"
  - TOXENV: "py34"

install:
  - C:\Python36\python -m pip install tox

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - C:\Python36\python -m tox
